apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: demo-vol
      mountPath: "/heros"
      readOnly: true
  resources:
      requests:
        cpu: 250m
        memory: "65M"
      limits:
        cpu: 500m
        memory: "130M"
  volumes:
  - name: demo-vol
    configMap:
      name: demo-heros